---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Create CloudFormation stack
      amazon.aws.cloudformation:
        stack_name: "ansible-cloudformation"
        state: "present"
        region: "eu-west-2"
        disable_rollback: true
        template: "stack.yml"
        template_parameters:
          KeyName: "cloudOneEuWest"
